build: don't redefine WIN32_LEAN_AND_MEAN
https://github.com/nodejs/node/pull/53722 added a new define for WIN32_LEAN_AND_MEAN
without first checking to see if it was defined - other areas in c-ares do this so
we should here as well. Compilation errors occur otherwise:

../../third_party/electron_node/deps/cares/include\ares_build.h(168,11): error: 'WIN32_LEAN_AND_MEAN' macro redefined [-Werror,-Wmacro-redefined]
  168 | #  define WIN32_LEAN_AND_MEAN
      |           ^
<command line>(25,9): note: previous definition is here
   25 | #define WIN32_LEAN_AND_MEAN 1
      |         ^
1 error generated.
[287 processes, 49437/51449 @ 48.5/s : 1018.562s] CC obj/third_party/electron_node/deps/cares/cares/ares__socket.obj
FAILED: obj/third_party/electron_node/deps/cares/cares/ares__socket.obj

This should be upstreamed.

Patch-Dir: src/electron/patches/node
Patch-Filename: build_don_t_redefine_win32_lean_and_mean.patch